#
# Dependabot Configuration Files
#
# List for "package-ecosystem": https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
#
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # Group all action updates in a single PR (instead of creating one PR per update).
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories: [ "**/*" ]
    schedule:
      interval: "daily"
