#
# Define default ACLs for Unbound.
#
# To clear these ACLs, provide your own file and bind-mount it over this file
# in Docker.
#
server:
    # Allow requests from RFC1918 private IPv4 address space (i.e. LANs).
    access-control: 10.0.0.0/8 allow
    # NOTE: Source IPs will be in this range if Docker port mapping is used for
    #   the container instead of 'network_mode: host'.
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow
