#
# Define the default listening interface for Unbound.
#
# To replace this interface, provide your own file and bind-mount it over this
# file in Docker. Adding an interface in another config file would leave this
# interface enabled as well.
#
server:
    # Make Unbound listen for requests from the Docker network. The default is to
    # listen only on 127.0.0.1/::1, which does not work for published container ports.
    interface: 0.0.0.0
