#
# To build this directly, use:
#
#     docker build -t test-image:local .
#

FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

COPY files/version.txt /version.txt

CMD ["sh"]
