#
# To build this directly, use:
#
#     docker build -t test-image:local .
#

FROM alpine:3.24@sha256:e7c4abb69531cb09e2a2bbb56fad3367ab694865c49df898c1c683185cc4376c

COPY files/version.txt /version.txt

CMD ["sh"]
