#
# To build this directly, use:
#
#     docker build -t test-image:local .
#

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

COPY files/version.txt /version.txt

CMD ["sh"]
