name: Publish Unbound image
run-name: "Publish Unbound image"

on:
  workflow_dispatch:
    inputs:
      treat_as_scheduled_run:
        description: "Treat as 'scheduled' run (for testing purposes)"
        type: boolean
        required: false
        default: false

jobs:
  publish-container-image:
    permissions:
      contents: read
      packages: write # for publishing new container images
    uses: ./.github/workflows/_publish-container-image.yml
    with:
      image-name: unbound
      treat_as_scheduled_run: ${{ github.event_name == 'workflow_dispatch' && inputs.treat_as_scheduled_run }}
