name: Publish Ansible devcontainer image
run-name: "Publish Ansible devcontainer image | ${{ github.event_name == 'schedule' && 'Scheduled' || github.event_name == 'workflow_dispatch' && 'Manual' || github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || github.event_name == 'push' && 'Push' || github.event_name }}"

on:
  push:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/_publish-container-image.yml"
      - ".github/workflows/publish-ansible-devcontainer.yml"
      - "ansible-devcontainer/**"
  schedule:
    # Every day at 00:41 UTC.
    - cron: "41 0 * * *"
  workflow_dispatch:
    inputs:
      treat_as_scheduled_run:
        description: "Treat as 'scheduled' run (for testing purposes)"
        type: boolean
        required: false
        default: false
  # PR validation is orchestrated by "build-gate.yml".
  workflow_call:

jobs:
  publish-container-image:
    permissions:
      contents: read
      packages: write # for publishing new container images
      actions: write  # for cancelling the workflow run
    uses: ./.github/workflows/_publish-container-image.yml
    with:
      image-name: ansible-devcontainer
      platforms: linux/amd64,linux/arm64
      comparison-method: version
      treat_as_scheduled_run: ${{ github.event_name == 'workflow_dispatch' && inputs.treat_as_scheduled_run }}
